### ISSUE TITLE
Issues creating Users in refinerycms 3.0, Rails 4.1

### ISSUE THREAD

**Issue by jamieEthington** [refinery/refinerycms#3021] opened 2015-07-29 15:59 UTC
When trying to create a user on my production site for refinery, I encountered an error screen. I tried to create a user locally, and got this error

Unknown primary key for table refinery_authentication_devise_roles_users in model Refinery::Authentication::Devise::User::HABTM_Roles.

I'm on the master branch. Any suggestions? I haven't messed around with user authentication at all, so I'm not sure what's causing the issue.

**Comment by bricesanchez** [comment] 2015-07-29 17:01
@jamieEthington Did you recently update your project?

**Comment by jamieEthington** [comment] 2015-07-29 17:25
@bricesanchez I guess I'm confused by your question - are you referring to a bundle update or something else?

**Comment by bricesanchez** [comment] 2015-07-29 17:27
@jamieEthington, Yes sorry, i'm speaking about a bundle update.

Could you paste your Gemfile + Gemfile.lock and the completete stacktrace ?

**Comment by qpowell** [comment] 2015-07-30 13:23
@bricesanchez I took a look at this project with Jamie, it looks like the issue may have actually been caused by refinerycms-authentication-devise.  It creates a join table called `refinery_authentication_devise_roles_users`. Creating a new join table named `refinery_authentication_devise_roles_refinery_authentication_devise_users` seems to fix it.

**Comment by bricesanchez** [comment] 2015-07-30 13:26
Could you open an issue in https://github.com/refinery/refinerycms-authentication-devise/issues with the all explanation to reproduce the error ?
or
Could you open a pull request to fix this error? :smiley: 

Thanks you very much

**Comment by qpowell** [comment] 2015-07-30 14:53
@bricesanchez I tried recreating it in a test app and I'm unable to reproduce it :) I'll see if there's an extra step he took that might've caused this. In the meantime, we can probably close this issue and if I find something I'll create an issue on the refinerycms-authentication-devise repo. Thanks!

**Closed** 2015-07-30 17:16 UTC
Labels: Awaiting Response, Needs verification
