### ISSUE TITLE
Get request for ?locale=en%20217 results in an error 

### ISSUE THREAD

**Issue by thebravoman** [refinery/refinerycms#3363] opened 2018-04-23 12:19 UTC
Not sure why, but I am receiving such requests. 
````
http://myapp/?locale=en%20217
````
The problem is that this results in 
````
undefined method `to_s=' for :en:Symbol
Did you mean?  to_s
               to_sym
````

The code in question is
find_or_set_locale refinerycms-i18n-b8bf5fa7c93e/lib/refinery/i18n/engine.rb  
````
if ::Refinery::I18n.has_locale?(locale = params[:locale].try(:to_sym))
              ::I18n.locale = locale
            elsif locale.present? && locale != ::Refinery::I18n.default_frontend_locale
              params[:locale] = ::I18n.locale.to_s = ::Refinery::I18n.default_frontend_locale.to_s
              redirect_to(params, :notice => "The locale '#{locale}' is not supported.") and return
            else
              ::I18n.locale = ::Refinery::I18n.default_frontend_locale
            end
````
Specifically
````
 params[:locale] = ::I18n.locale.to_s = ::Refinery::I18n.default_frontend_locale.to_s
````
 ::I18n.locale.to_s should not be assigned a value. Right?

**Comment by bricesanchez** [comment] 2018-04-24 01:34
Hi @thebravoman!

Thanks for your report!

It looks like this code needs some fresh refactoring but i think you're right. Why should we try to assign this `::I18n.locale` if we try to say this locale is not supported.

Could you provide a pull request to fix this strange behavior?

Am I missing something @parndt?

**Comment by parndt** [comment] 2018-04-24 02:15
correct

**Comment by bricesanchez** [comment] 2018-04-30 12:56
Hi @thebravoman, could you try this PR to see if it fixes your issue : https://github.com/refinery/refinerycms-i18n/pull/77

**Comment by bricesanchez** [comment] 2018-05-11 04:15
Hi @thebravoman, I've come back on my PR and i realized that i'm not able to reproduce your problem.

Could you give a step by step to reproduce on a dummy_app?
Could you give me your Gemfile.lock?

Thanks!

**Comment by bricesanchez** [comment] 2018-05-15 12:00
Hi @thebravoman, could you check this new PR?

**Closed** 2018-05-16 08:38 UTC
Labels: Accepted, Needs discussion
