### ISSUE TITLE
Malformed DIV TAG using background url property

### ISSUE THREAD

**Issue by cristianoveiga** [refinery/refinerycms#3233] opened 2016-07-25 15:46 UTC
Hello,

I've installed Refinery on my existing Rails 4.2 application.

Everything works well, except for the following situation:

When I add a div and set a background image, for some reason the HTML generated in the final page has a malformed tag (see attached  image).

It's weird because it works for some other CSS attributes/properties, for example: CSS class and width/height.

Please, could you help me with this issue ?

Thank you.

Cristiano Veiga

![screen shot 07-25-16 at 11 36 am](https://cloud.githubusercontent.com/assets/120203/17107406/0c167148-525d-11e6-90d9-7837be697359.PNG)

**Comment by bricesanchez** [comment] 2016-07-25 17:12
Hello,

What is your version of refinery?

It could be the HTML sanitizer.

Did you see any warning in your rails server log?

**Comment by cristianoveiga** [comment] 2016-07-25 17:21
Hello Brice,

I'm using refinerycms (3.0.4).

You are right, it's the Sanitizer (see attached).

![image](https://cloud.githubusercontent.com/assets/120203/17110346/9064a462-526a-11e6-9bed-1a7614b4303b.png)

Do you have any idea how can I deal with it ?

Thanks,

Cristiano

**Comment by bricesanchez** [comment] 2016-07-25 18:35
The best is to not have inline CSS.

I don't know why it does not allow `style` this attribute is present in `Loofah::HTML5::WhiteList` : https://github.com/flavorjones/loofah/blob/v2.0.3/lib/loofah/html5/whitelist.rb#L78

**Comment by bricesanchez** [comment] 2016-07-25 18:36
What happens if you add a `;` at the end of the CSS definition ?

**Comment by cristianoveiga** [comment] 2016-07-25 18:46
Well,

I usually try to not to put inline CSSs most of the times, but for this case I don't see any alternative.

The context is: I wanna be able to customize the background image of some divs in my pages.

I tried to put the ; but I got the same behaviour:

![image](https://cloud.githubusercontent.com/assets/120203/17112963/573f53b0-5276-11e6-86c4-3b3a8c47b684.png)

Any ideas ?

Thanks again !

**Comment by bricesanchez** [comment] 2016-08-29 13:46
Did you find the solution?

**Comment by cristianoveiga** [comment] 2016-08-29 14:23
Hi Brice,

Not yet.

Do you have any suggestion ?

Thanks.

**Comment by bricesanchez** [comment] 2016-08-29 15:09
On a `refinerycms (3.0.3)` project, i have: 

```slim
[...]
      .row
        - if post.images.any?
          .img.mobile style="background-image:url(#{post.images.first.thumbnail(geometry: "720x224").url});"
          .img.desktop style="background-image:url(#{post.images.first.thumbnail(geometry: "270x200").url});"
[...]
```

And inline `style` works well.

You probably have a problem in your code.

Could you show me your view ?

**Comment by bricesanchez** [comment] 2016-11-10 14:13
Is it fixed for you ?

**Comment by cristianoveiga** [comment] 2016-11-18 00:06
Hi Brice,

Sorry for not replying before.

Actually I'm no longer working on this project/company.

In the end, we gave up using Refinery for that purpose.

Thank you so much for your time and feel free to close the issue.

Cristiano

**Comment by bricesanchez** [comment] 2016-11-18 02:28
@cristianoveiga thanks for your answer, i close this issue because i'm not able to reproduce the error.

**Closed by bricesanchez** 2016-11-18 02:28 UTC
Labels: 3-0-stable, Awaiting Response
