### ISSUE TITLE
Refinery cms Initial step facing page not found issue in root url

### ISSUE THREAD

**Issue by arokia-innominds** [refinery/refinerycms#3086] opened 2016-01-05 09:20 UTC
After I am installing Refinery-CMS, facing page not found issue in root url, instead of that redirected registration url or login page of the application

**Comment by bricesanchez** [comment] 2016-01-06 14:52
Could you paste us your Gemfile.lock and steps to reproduce this error ?

**Comment by arokia-innominds** [comment] 2016-01-11 06:57
refinerycms (3.0.0 d91d3fe)
  * refinerycms-acts-as-indexed (2.0.1)
  * refinerycms-authentication-devise (1.0.4)
  * refinerycms-core (3.0.0 d91d3fe)
  * refinerycms-i18n (3.0.1)
  * refinerycms-images (3.0.0 d91d3fe)
  * refinerycms-pages (3.0.0 d91d3fe)
  * refinerycms-resources (3.0.0 d91d3fe)
  * refinerycms-wymeditor (1.0.6)
![screen shot 2016-01-11 at 12 26 34 pm](https://cloud.githubusercontent.com/assets/10205135/12228252/9ea916d0-b85e-11e5-8cf5-9c98a2403965.png)

**Comment by bricesanchez** [comment] 2016-01-11 16:13
I think it's because you didn't ran `rake db:seed`, you've not created the default pages contained in this seed : https://github.com/refinery/refinerycms/blob/master/pages/db/seeds.rb

**Comment by bricesanchez** [comment] 2016-01-27 05:05
Could i close this issue ?

**Comment by arokia-innominds** [comment] 2016-01-27 05:09
Yes fine

**Closed** 2016-01-27 05:10 UTC
