### ISSUE TITLE
Display bug with WYMeditor, the iframe takes more space and not showing in view

### ISSUE THREAD

**Issue by ttmthanh** [refinery/refinerycms#3496] opened 2021-05-13 03:45 UTC
I embed video into my web page, not show but in my wymeditor it show. Please help me. When I embed this video, it display in WYMeditor, but view not showing

![ảnh](https://user-images.githubusercontent.com/22828586/124901518-495d1b00-e00c-11eb-9c15-cbfdc8ba6a4f.png)

**Comment by parndt** [comment] 2021-07-08 20:53
Duplicate of #1425

**Closed by parndt** 2021-07-08 20:53 UTC
