### ISSUE TITLE
404 with template urls

### ISSUE THREAD

**Issue by Gavxn** [refinery/refinerycms#3304] opened 2017-07-22 03:19 UTC
There's an issue with these template urls which are shown in the readme.
* http://refinerycms.com/t/3-0-stable
* http://refinerycms.com/t/edge

This is causing:
`ruby-2.3.1/lib/ruby/2.3.0/open-uri.rb:359:in open_http': 404 Not Found (OpenURI::HTTPError)` 
when making a new project:
`rails new my_app -m http://refinerycms.com/t/3-0-stable`.

**Comment by bricesanchez** [comment] 2017-07-22 04:04
The problem is causes by the new website, i fix it ASAP

**Comment by bricesanchez** [comment] 2017-07-22 04:13
This should be fixed now with this commit: https://github.com/refinery/website/commit/98a82cf1589696c8789f14a612b97a47179486bb

Sorry for the inconvenience

**Closed by bricesanchez** 2017-07-22 04:13 UTC
Labels: Accepted

**Comment by Gavxn** [comment] 2017-07-22 16:17
Thanks for the quick fix.
